# Generated by Django 2.2.4 on 2019-09-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinyinCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=10)),
                ('pinyin1', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('pinyin2', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Pinyin Database Model',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('input_string', models.TextField(max_length=1000)),
                ('ip_address', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'User Input Model',
                'db_table': 'User_Input',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='userinput',
            index=models.Index(fields=['created'], name='created_idx'),
        ),
        migrations.AddIndex(
            model_name='pinyincodes',
            index=models.Index(fields=['character'], name='character_index'),
        ),
    ]
