# Generated by Django 2.2.4 on 2019-09-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinyin', '0002_auto_20190914_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='input_string',
            field=models.TextField(max_length=2000),
        ),
    ]
